# Generated by Django 3.2.20 on 2023-08-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_reading', models.CharField(default=None, max_length=150, null=True)),
                ('bill_amount', models.IntegerField(default=0, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bills.meter')),
            ],
        ),
    ]
