# Generated by Django 3.2.20 on 2023-08-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('meter_owner', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('meter_type', models.CharField(choices=[('Electicity', 'Electricity'), ('Gas', 'Gas'), ('Water', 'Water')], default='E', max_length=30)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Area.areas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculatedBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('bill_total_amount', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('bill_reading_img', models.ImageField(default=None, upload_to='./images')),
                ('bill_reading', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('bill_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default=None, max_length=50, null=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bills.meter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
