# Generated by Django 3.2.20 on 2023-08-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedbills',
            name='payment_recieved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculatedbills',
            name='remaing_dues',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
