# Generated by Django 3.2.20 on 2023-09-22 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0005_calculatedbill_units_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedbill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
