# Generated by Django 3.2.20 on 2023-09-22 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0006_alter_calculatedbill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedbill',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 20, 41, 28, 369221, tzinfo=utc)),
        ),
    ]
