# Generated by Django 3.2.20 on 2024-01-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0008_auto_20230922_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedbill',
            name='bill_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('ipaid', 'Initialy Paid')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calculatedbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
