# Generated by Django 3.2.20 on 2023-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owners_name', models.CharField(blank=True, default=None, max_length=155, null=True)),
                ('house_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('CNIC', models.CharField(default=None, max_length=20, null=True)),
                ('area_block', models.CharField(default=None, max_length=10, null=True)),
                ('meter_no', models.CharField(default=None, max_length=50, null=True)),
                ('area_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], default='commercial', max_length=50)),
                ('bill_paid_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
    ]
