# Generated by Django 3.2.20 on 2023-08-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0003_alter_calculatedbills_bill_total_amount'),
        ('Area', '0002_areas_owners_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
    ]
