# Generated by Django 4.2.2 on 2023-08-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residential_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('commercial_unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('fine_after_due_date', models.IntegerField(blank=True, default=0, null=True)),
                ('miscellaneous_charges', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
