# Generated by Django 4.2.2 on 2023-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnitsRate', '0004_unitvalues200orless_unitvalues400orless_unitvalues600orless'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdRangeOfUnitValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_of_units_residential', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unit_price_for_third_range_residentails', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('range_of_units_commercial', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unit_price_for_third_range_wdcommercial', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UnitValues600OrLess',
            new_name='FirstRangeOfUnitValues',
        ),
        migrations.RenameModel(
            old_name='UnitValues400OrLess',
            new_name='FouthRangeOfUnitValues',
        ),
        migrations.RenameModel(
            old_name='UnitValues200OrLess',
            new_name='SecondtRangeOfUnitValues',
        ),
        migrations.RenameField(
            model_name='firstrangeofunitvalues',
            old_name='range_for_600_or_less_commercial',
            new_name='range_of_units_commercial',
        ),
        migrations.RenameField(
            model_name='firstrangeofunitvalues',
            old_name='range_for_600_or_less_residentials',
            new_name='range_of_units_residential',
        ),
        migrations.RenameField(
            model_name='firstrangeofunitvalues',
            old_name='unit_price_for_600_less_units_commercial',
            new_name='unit_price_for_first_range_residentails',
        ),
        migrations.RenameField(
            model_name='firstrangeofunitvalues',
            old_name='unit_price_for_600_less_units_residentials',
            new_name='unit_price_for_first_range_wdcommercial',
        ),
        migrations.RenameField(
            model_name='fouthrangeofunitvalues',
            old_name='range_for_400_or_less_commercial',
            new_name='range_of_units_commercial',
        ),
        migrations.RenameField(
            model_name='fouthrangeofunitvalues',
            old_name='range_for_400_or_less_residentials',
            new_name='range_of_units_residential',
        ),
        migrations.RenameField(
            model_name='fouthrangeofunitvalues',
            old_name='unit_price_for_400_less_units_commercial',
            new_name='unit_price_for_fourht_range_residentails',
        ),
        migrations.RenameField(
            model_name='fouthrangeofunitvalues',
            old_name='unit_price_for_400_less_units_residentials',
            new_name='unit_price_for_fourth_range_wdcommercial',
        ),
        migrations.RenameField(
            model_name='secondtrangeofunitvalues',
            old_name='range_for_200_or_less_commercial',
            new_name='range_of_units_commercial',
        ),
        migrations.RenameField(
            model_name='secondtrangeofunitvalues',
            old_name='range_for_200_or_less_residential',
            new_name='range_of_units_residential',
        ),
        migrations.RenameField(
            model_name='secondtrangeofunitvalues',
            old_name='unit_price_for_200_less_units_commercial',
            new_name='unit_price_for_second_range_residentails',
        ),
        migrations.RenameField(
            model_name='secondtrangeofunitvalues',
            old_name='unit_price_for_200_less_units_residentails',
            new_name='unit_price_for_second_range_wdcommercial',
        ),
    ]
