# Generated by Django 3.2.20 on 2023-09-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnitsRate', '0005_thirdrangeofunitvalues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDateForFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
