# Generated by Django 3.2.20 on 2023-09-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UnitsRate', '0006_duedateforfine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FouthRangeOfUnitValues',
            new_name='FirstRangeOfUnitValue',
        ),
        migrations.RenameModel(
            old_name='FirstRangeOfUnitValues',
            new_name='FouthRangeOfUnitValue',
        ),
        migrations.RenameModel(
            old_name='ThirdRangeOfUnitValues',
            new_name='SecondRangeOfUnitValue',
        ),
        migrations.RenameModel(
            old_name='SecondtRangeOfUnitValues',
            new_name='ThirdRangeOfUnitValue',
        ),
        migrations.RenameField(
            model_name='firstrangeofunitvalue',
            old_name='unit_price_for_fourht_range_residentails',
            new_name='unit_price_for_first_range_residentails',
        ),
        migrations.RenameField(
            model_name='firstrangeofunitvalue',
            old_name='unit_price_for_fourth_range_wdcommercial',
            new_name='unit_price_for_first_range_wdcommercial',
        ),
        migrations.RenameField(
            model_name='fouthrangeofunitvalue',
            old_name='unit_price_for_first_range_residentails',
            new_name='unit_price_for_fourht_range_residentails',
        ),
        migrations.RenameField(
            model_name='fouthrangeofunitvalue',
            old_name='unit_price_for_first_range_wdcommercial',
            new_name='unit_price_for_fourth_range_wdcommercial',
        ),
        migrations.RenameField(
            model_name='secondrangeofunitvalue',
            old_name='unit_price_for_third_range_residentails',
            new_name='unit_price_for_second_range_residentails',
        ),
        migrations.RenameField(
            model_name='secondrangeofunitvalue',
            old_name='unit_price_for_third_range_wdcommercial',
            new_name='unit_price_for_second_range_wdcommercial',
        ),
        migrations.RenameField(
            model_name='thirdrangeofunitvalue',
            old_name='unit_price_for_second_range_residentails',
            new_name='unit_price_for_third_range_residentails',
        ),
        migrations.RenameField(
            model_name='thirdrangeofunitvalue',
            old_name='unit_price_for_second_range_wdcommercial',
            new_name='unit_price_for_third_range_wdcommercial',
        ),
    ]
